<?php

namespace Database\Seeders;

use App\Models\Age;
use App\Models\AgeFactor;
use App\Models\AnnualBaseRate;
use App\Models\FormCard;
use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        User::factory()->create([
            'name' => 'admin',
            'name' => 'admin',
            'email' => 'admin@example.com',
        ]);
        
        User::factory()->create([
            'name' => 'agent',
            'name' => 'agent',
            'email' => 'agent@example.com',
        ]);

        User::factory()->create([
            'name' => 'client',
            'name' => 'client',
            'email' => 'client@example.com',
        ]);


        
        //value 2500
        $annualBaseRate= 3000;
        AnnualBaseRate::create(['value'=>$annualBaseRate]);

        // expected life
        $expected = ['EL08', 'EL09', 'EL10', 'EL11', 'EL12', 'EL13', 'EL14', 'EL15', 'EL16', 'EL17', 'EL18', 'EL19+'];
        foreach ($expected as $ex) {
            DB::table('expected_lives')->insert([
                'name' => $ex,
            ]);
        }


        // ages
        $dataAge = [
            ['age'=>'inférieur à 1'],
            ['age'=>'1 an'],
            ['age'=>'2 ans'],
            ['age'=>'3 ans'],
            ['age'=>'4 ans'],
            ['age'=>'5 ans'],
            ['age'=>'6 ans'],
            ['age'=>'7 ans'],
            ['age'=>'8 ans'],
            ['age'=>'9 ans'],
            ['age'=>'10 ans'],
            ['age'=>'11 ans'],
            ['age'=>'12 ans'],
            ['age'=>'13 ans'],
            ['age'=>'14 ans'],
            ['age'=>'14 ans'],
            ['age'=>'16 ans'],
            ['age'=>'17 ans'],
            ['age'=>'18 ans'],
            ['age'=>'19 ans'],
            ['age'=>'20 ans'],
        ];
        foreach ($dataAge as $type) {
            Age::create($type);
        }

        // age factor
        $data = [
            [0.97, 0.96, 0.96, 0.95, 0.93, 0.93, 0.93, 0.93, 0.93, 0.93, 0.93, 0.93],
            [0.97, 0.96, 0.96, 0.95, 0.93, 0.93, 0.93, 0.93, 0.93, 0.93, 0.93, 0.93],
            [0.97, 0.96, 0.96, 0.95, 0.93, 0.93, 0.93, 0.93, 0.93, 0.93, 0.93, 0.93],
            [1.119, 1.023, 0.96, 0.95, 0.93, 0.93, 0.93, 0.93, 0.93, 0.93, 0.93, 0.93],
            [1.4501, 1.2991, 1.2016, 1.1098, 1.0374, 0.982, 0.93, 0.93, 0.93, 0.93, 0.93, 0.93],
            [1.8899, 1.6455, 1.4889, 1.3564, 1.2537, 1.1741, 1.1039, 1.0458, 0.9932, 0.93, 0.93, 0.93],
            [2.4748, 2.1037, 1.8533, 1.6565, 1.5095, 1.3981, 1.3036, 1.2258, 1.1564, 1.0997, 1.0435, 1.001],
            [3.1182, 2.6799, 2.3224, 2.0367, 1.8237, 1.6651, 1.536, 1.4324, 1.3425, 1.2693, 1.1988, 1.1439],
            [3.5112, 3.2778, 2.8814, 2.5107, 2.2164, 1.993, 1.8148, 1.6744, 1.5566, 1.4618, 1.3738, 1.3046],
            [3.5112, 3.6419, 3.4339, 3.0523, 2.6901, 2.3942, 2.1542, 1.9646, 1.8086, 1.6844, 1.5731, 1.4855],
            [3.5112, 3.6419, 3.7668, 3.5704, 3.2126, 2.8638, 2.5607, 2.3132, 2.1092, 1.9464, 1.8043, 1.6923],
            [3.5112, 3.6419, 3.7668, 3.8861, 3.6998, 3.3667, 3.0239, 2.7218, 2.4649, 2.256, 2.0755, 1.932],
            [3.5112, 3.6419, 3.7668, 3.8861, 3.9999, 3.8262, 3.5084, 3.177, 2.8739, 2.6168, 2.3927, 2.2114],
            [3.5112, 3.6419, 3.7668, 3.8861, 3.9999, 4.1123, 3.9444, 3.6436, 3.3207, 3.0244, 2.7572, 2.5345],
            [3.5112, 3.6419, 3.7668, 3.8861, 3.9999, 4.1123, 4.2198, 4.0585, 3.7715, 3.4622, 3.1625, 2.9005],
            [3.5112, 3.6419, 3.7668, 3.8861, 3.9999, 4.1123, 4.2198, 4.324, 4.1691, 3.8979, 3.5919, 3.3017],
            [3.5112, 3.6419, 3.7668, 3.8861, 3.9999, 4.1123, 4.2198, 4.324, 4.4278, 4.2798, 4.0148, 3.7213],
            [3.5112, 3.6419, 3.7668, 3.8861, 3.9999, 4.1123, 4.2198, 4.324, 4.4278, 4.5319, 4.3841, 4.1305],
            [3.5112, 3.6419, 3.7668, 3.8861, 3.9999, 4.1123, 4.2198, 4.324, 4.4278, 4.5319, 4.6325, 4.4861],
            [3.5112, 3.6419, 3.7668, 3.8861, 3.9999, 4.1123, 4.2198, 4.324, 4.4278, 4.5319, 4.6325, 4.7283]
        ];
        
        $expectedIds = range(1, 12); // Tableau de 1 à 12
        $ageIds = range(1, 20); // Tableau de 1 à 19 (y compris "19+")

        // Parcourez les âges
        foreach ($ageIds as $ageId) {
            // Parcourez les valeurs attendues (expected_life_id)
            foreach ($expectedIds as $expectedId) {
                // Insérez les données dans la table AgeFactor
                AgeFactor::create([
                    'value' => $data[$ageId - 1][$expectedId - 1],
                    'expected_life_id' => $expectedId,
                    'age_id' => $ageId,
                ]);
            }
        }

        //type race
        $breedType = ['chat','chien'];
        foreach ($breedType as $type) {
            DB::table('breed_types')->insert([
                'name' => $type,
            ]);
        }

        //races
        $race =
            [
                'chien' => [
                    "Affenpinscher",
                    "Afghan Hound",
                    "Airedale Terrier",
                    "Akbash",
                    "Akita",
                    "Alaskan Husky",
                    "Alaskan Malamute",
                    "American Alaskan Spitz",
                    "American Bandogge Mastiff",
                    "American Black and Tan Coonhound",
                    "American Blue Gascon Hound",
                    "American Bulldog",
                    "American Cocker Spaniel",
                    "American English Coonhound",
                    "American Eskimo",
                    "American Eskimo-Miniature",
                    "American Foxhound",
                    "American Indian",
                    "American Hairless Terrier",
                    "American Mastiff",
                    "American Mastiff (Panja)",
                    "American Pit Bull",
                    "American Pitbull Terrier",
                    "American Royal Retriever",
                    "American Staffordshire Bull Terrier",
                    "American Staffordshire Terrier",
                    "American Staghound",
                    "American Tundra Shepherd",
                    "American Water Spaniel",
                    "Anatolian",
                    "Anatolian Shepherd",
                    "Appenzeller Sennenhunde",
                    "Argentine Dogo",
                    "Australian Cattle Dog",
                    "Australian Dingo",
                    "Australian Kelpie",
                    "Australian Shepherd",
                    "Australian Shepherd-Miniature",
                    "Australian Silky Terrier",
                    "Australian Stumpy Tail Cattle",
                    "Australian Terrier",
                    "Azawakh Hound",
                    "Barbet",
                    "Basenji",
                    "Basset Fauve de Bretagne",
                    "Basset Hound",
                    "Bavarian Mountain Hound",
                    "Beagle",
                    "Bearded Collie",
                    "Beauceron",
                    "Bedlington Terrier",
                    "Belgian Laekenois",
                    "Belgian Malinois",
                    "Belgian Mastiff",
                    "Belgian Sheepdog",
                    "Belgian Shepherd",
                    "Belgian Tervuren",
                    "Bergamasco Sheepdog",
                    "Berger Des Pyrénées",
                    "Berger Picard/Picardy Sheepdog",
                    "Bernese Mountain Dog",
                    "Bichon Frise",
                    "Black and Tan Coonhound",
                    "Black Russian Terrier",
                    "Blackmouth Cur",
                    "Bloodhound",
                    "Blue Heeler",
                    "Blue Picardy Spaniel",
                    "Blue Tick Coonhound",
                    "Boerboel",
                    "Bolognese",
                    "Border Collie",
                    "Border Terrier",
                    "Borzoi/Russian Wolfhound",
                    "Boston Terrier",
                    "Bouvier des Flandres",
                    "Boxer",
                    "Boykin Spaniel",
                    "Bracco Italiano",
                    "Brazilian Fila",
                    "Briard",
                    "Brittany",
                    "Brussels Griffon",
                    "Bull Boxer",
                    "Bull Terrier",
                    "Bull Terrier-Miniature",
                    "Bulldog",
                    "Bullmastiff",
                    "Cairn Terrier",
                    "Canaan Dog",
                    "Canadian Eskimo/Inuit",
                    "Canary Dog",
                    "Cane Corso",
                    "Cardigan Welsh Corgi",
                    "Catahoula Leopard Dog",
                    "Caucasian Ovcharka",
                    "Cavalier King Charles Spaniel",
                    "Central Asian Shepherd",
                    "Cesky Terrier",
                    "Chanille",
                    "Chesapeake Bay Retriever",
                    "Chihuahua",
                    "Chihuahua-Long-Haired",
                    "Chinese Crested",
                    "Chinese Crested Powder Puff",
                    "Chinese Pug",
                    "Chinook",
                    "Chipom",
                    "Chipoo",
                    "Chow Chow",
                    "Cirneco dell Etna",
                    "Clumber Spaniel",
                    "Cockapoo",
                    "Cocker Spaniel",
                    "Cocker Spaniel-Miniature",
                    "Collie",
                    "Collie - Smooth Coated",
                    "Coonhound",
                    "Coonhound-Black & Tan",
                    "Coonhound-Blue Tick",
                    "Coonhound-Redbone",
                    "Coton de Tulear",
                    "Curly-Coated Retriever",
                    "Czechoslovakian Wolfdog",
                    "Dachshund",
                    "Dachshund-Long Haired",
                    "Dachshund-Miniature",
                    "Dachshund-Miniature Long Haired",
                    "Dachshund-Miniature Smooth Haired",
                    "Dachshund-Miniature Wire Hair",
                    "Dachshund-Wire Haired",
                    "Dalmatian",
                    "Dandie Dinmont Terrier",
                    "Deerhound",
                    "Designer / Hybrid",
                    "Dingo/Carolina",
                    "Doberman Pinscher",
                    "Dogue de Bordeaux",
                    "Drever",
                    "Dunker/Norwegian Hound",
                    "Dutch Sheepdog",
                    "English Bull",
                    "English Bulldog",
                    "English Cocker Spaniel",
                    "English Foxhound",
                    "English Mastiff",
                    "English Pointer",
                    "English Setter",
                    "English Shepherd",
                    "English Springer Spaniel",
                    "English Toy Spaniel",
                    "English Toy Terrier",
                    "Entlebucher Mountain Dog",
                    "Estrela Mountain Dog",
                    "Eurasian/Eurasier",
                    "Field Spaniel",
                    "Fila Brasileiro/Brazillian Mastiff",
                    "Finnish Hound",
                    "Finnish Lapphund",
                    "Finnish Spitz",
                    "Flat-Coated Retriever",
                    "Formosan (Taiwanese) Mountain Dog",
                    "Fourche Terrier",
                    "Fox Terrier",
                    "French Bulldog",
                    "French Mastiff",
                    "French Spaniel",
                    "Ganaraskan",
                    "Gascogne Braque Francais",
                    "German Pinscher",
                    "German Pointer",
                    "German Wirehaired Pointer",
                    "German Shepherd",
                    "German Spitz",
                    "German/Mittel Spitz",
                    "Giant Schnauzer",
                    "Glen of Imaal Terrier",
                    "Golden Retriever",
                    "Goldendoodle",
                    "Gordon Setter",
                    "Grand Basset Griffon Vendéen",
                    "Great Dane",
                    "Great Pyrenees",
                    "Greater Swiss Mountain Dog",
                    "Greenland Dog",
                    "Greyhound",
                    "Groenendael Belgian Shepherd",
                    "Hamiltonstovare",
                    "Harrier",
                    "Havanese",
                    "Hovawart",
                    "Hungarian Sheepdog",
                    "Ibizan Hound",
                    "Icelandic Sheepdog",
                    "Inca Orchid",
                    "Irish Setter",
                    "Irish Terrier",
                    "Irish Water Spaniel",
                    "Irish Wolfhound",
                    "Italian Bulldogge",
                    "Italian Greyhound",
                    "Jack Russell Terrier",
                    "Japanese Chin",
                    "Japanese Spaniel",
                    "Japanese Spitz",
                    "Japanese Terrier",
                    "Jindo",
                    "Kai Ken",
                    "Karelian Bear Dog",
                    "Keeshond",
                    "Kelpie",
                    "Kerry Blue Terrier",
                    "Kishu Ken",
                    "Komondor",
                    "Kooikerhondje",
                    "Kuvasz",
                    "Kyi-Leo",
                    "Labradoodle",
                    "Labrador Retriever",
                    "Laekenois Belgian Shepherd",
                    "Lagotto Romagnolo",
                    "Lakeland Terrier",
                    "Lancashire Heeler",
                    "Landseer",
                    "Large Munsterlander",
                    "Leonberger",
                    "Lhasa Apso",
                    "Louisiana Catahoula Hog Dog",
                    "Lowchen",
                    "Llewellin Setter",
                    "Malamute Husky",
                    "Malinois Belgian Shepherd",
                    "Maltese",
                    "Maltipoo",
                    "Manchester Terrier",
                    "Maremma",
                    "Mastiff",
                    "Mexican Hairless",
                    "Mexican Hairless-Crested",
                    "Mi-Ki",
                    "Miniature Australian Shepherd",
                    "Miniature Bull Terrier",
                    "Miniature Dachshund",
                    "Miniature Pinscher",
                    "Miniature Poodle",
                    "Miniature Schnauzer",
                    "Mixed Breed - Dog",
                    "Mountain Cur",
                    "Mountain Terrier",
                    "Mudi",
                    "Münsterländer",
                    "Native American Indian",
                    "Neapolitan Mastiff",
                    "Nebolish Mastiff",
                    "New Zealand Huntaway",
                    "New Zealand Sheepdog",
                    "Newfoundland",
                    "Norfolk Terrier",
                    "Norrbottenspets",
                    "Norwegian Buhund",
                    "Norwegian Elkhound",
                    "Norwegian/Norsk Lundehund",
                    "Norwegian Viking Buhund",
                    "Norwich Terrier",
                    "Nova Scotia Duck Tolling Retriever",
                    "Old Boston Bulldogge",
                    "Old English Mastiff",
                    "Old English Sheepdog",
                    "Old Victorian Bulldogge",
                    "Olde English Bulldog",
                    "Otterhound",
                    "Papillon",
                    "Parson Russell Terrier",
                    "Patterdale/Fell Terrier",
                    "Pekingese",
                    "Pembroke Welsh Corgi",
                    "Perro de Presa Canario",
                    "Peruvian Hairless",
                    "Peruvian Inca Orchid",
                    "Petit Basset Griffon Vendeen",
                    "Pharaoh Hound",
                    "Picardy Spaniel",
                    "Pitbull",
                    "Plott",
                    "Pointer",
                    "Polish Lowland Sheepdog",
                    "Polish Tatra",
                    "Polski Ocharch Nizinny",
                    "Pomapoo",
                    "Pomeranian",
                    "Poodle",
                    "Poodle-Standard",
                    "Poodle-Teacup",
                    "Poodle-Toy",
                    "Porkie",
                    "Portuguese Podengo",
                    "Portuguese Podenjo Pequeno",
                    "Portuguese Pointer",
                    "Portuguese Water Dog",
                    "Prague Ratter",
                    "Pudelpointer",
                    "Pug",
                    "Puggle",
                    "Puli",
                    "Pumi",
                    "Pyrenean Mastiff",
                    "Pyrenean Mountain Dog (Great Pyrenees)",
                    "Pyrenean Sheepdog",
                    "Pyrenean Shepherd",
                    "Pyrenees Braque Francais",
                    "Queensland Heeler",
                    "Rafeiro do Alentejo",
                    "Rare Breed",
                    "Rat Terrier",
                    "Redbone Coonhound",
                    "Rhodesian Ridgeback",
                    "Roman Rottweiler",
                    "Rottweiler",
                    "Russian Bolonka",
                    "Russian Hound",
                    "Russian Toy",
                    "Russian Wolfhound",
                    "Saint Bernard",
                    "Saluki (Gazelle Hound)",
                    "Samoyed",
                    "Schapendoes",
                    "Schipperke",
                    "Schnauzer-Giant",
                    "Schnauzer-Miniature",
                    "Schnauzer-Standard",
                    "Schnoodle",
                    "Scottish Deerhound",
                    "Scottish Terrier",
                    "Sealyham Terrier",
                    "Segugio Italiano",
                    "Shar Pei",
                    "Sheltie",
                    "Shetland Sheepdog",
                    "Shiba Inu",
                    "Shih Tzu",
                    "Shikoku",
                    "Shiloh Shepherd",
                    "Siberian Husky",
                    "Silken Windhound",
                    "Silky Terrier",
                    "Skye Terrier",
                    "Sloughi",
                    "Slovensky Cuvac",
                    "Small Munsterlander",
                    "Smooth Fox Terrier",
                    "Snoodle",
                    "Soft Coated Wheaten Terrier",
                    "Spanish Bulldog",
                    "Spanish Mastiff",
                    "Spanish Water Dog",
                    "Spinone Italiano",
                    "Spitz",
                    "St. Johns Waterdog",
                    "Stabyhoun (Stabij)",
                    "Staffordshire Bull Terrier",
                    "Standard Schnauzer",
                    "Sussex Spaniel",
                    "Swedish Elkhound",
                    "Swedish Lapphund",
                    "Swedish Vallhund",
                    "Telomian",
                    "Terrier",
                    "Terripoo",
                    "Tervuren Belgian Shepherd",
                    "Texas Blue Lacey",
                    "Thai",
                    "Thai Ridgeback",
                    "Tibetan Mastiff",
                    "Tibetan Spaniel",
                    "Tibetan Terrier",
                    "Tosa",
                    "Toy Fox Terrier",
                    "Toy Terrier",
                    "Toy Manchester Terrier",
                    "Toy Poodle",
                    "Treeing Tennessee Brindle",
                    "Treeing Walker Coon Hound",
                    "Victorian Bulldog",
                    "Vizsla",
                    "Walker Hound",
                    "Weimaraner",
                    "Welsh Corgi-Cardigan",
                    "Welsh Corgi-Pembroke",
                    "Welsh Sheepdog (Welsh Collie)",
                    "Welsh Springer Spaniel",
                    "Welsh Terrier",
                    "West Highland White Terrier",
                    "Westmoreland Terrier",
                    "Wheaten Terrier",
                    "Whippet",
                    "White Doberman",
                    "Wire Haired Fox Terrier",
                    "Wirehaired Pointing Griffon",
                    "Wirehaired Vizsla",
                    "Xoloscuintle",
                    "Yorkiepoo",
                    "Yorkshire Terrier"
                ],
                // les chat
                'Chat' => [
                    "Abyssinian",
                    "American Bobtail",
                    "American Curl",
                    "American Long Hair",
                    "American Shorthair",
                    "American Wirehair",
                    "Angora",
                    "Balinese",
                    "Bengal",
                    "Birman",
                    "Bombay",
                    "British Longhair",
                    "British Shorthair",
                    "Bullseye",
                    "Burmese",
                    "California Spangled",
                    "Chartreux",
                    "Chausie",
                    "Chinchilla Persian",
                    "Colorpoint Shorthair",
                    "Cornish Rex",
                    "Cymric",
                    "Devon Rex",
                    "Domestic Longhair",
                    "Domestic Mediumhair",
                    "Domestic Shorthair",
                    "Donskoy",
                    "Egyptian Mau",
                    "Exotic Longhair",
                    "Exotic Shorthair",
                    "Havana Brown",
                    "Himalayan",
                    "Japanese Bobtail",
                    "Javanese",
                    "Korat",
                    "LaPerm",
                    "Maine Coon",
                    "Manx",
                    "Manx Longhair",
                    "Mixed Breed - Cat",
                    "Munchkin",
                    "Nebelung",
                    "Norwegian Forest",
                    "Ocicat",
                    "Ojos Azules",
                    "Oriental",
                    "Persian",
                    "Persian-Himalayan",
                    "Peterbald",
                    "Pixiebob",
                    "Ragdoll",
                    "Rex",
                    "Russian Blue",
                    "Savannah",
                    "Scottish Fold",
                    "Selkirk Rex",
                    "Serengeti",
                    "Shorthair Chinchilla",
                    "Siamese",
                    "Siberian",
                    "Singapura",
                    "Snowshoe",
                    "Somali",
                    "Sphynx",
                    "Tiffany",
                    "Tonkinese",
                    "Toyger",
                    "Turkish Angora",
                    "Turkish Van",
                    "York Chocolate"
                ]
            ];

        // DataRaces
        $breedData = [
            ["name" => "Abyssinian", "expected_life_id" => 6, "breed_factor" => 0.6410],
            ["name" => "Affenpinscher", "expected_life_id" => 7, "breed_factor" => 0.8948],
            ["name" => "Afghan Hound", "expected_life_id" => 6, "breed_factor" => 1.1000],
            ["name" => "Airedale Terrier", "expected_life_id" => 6, "breed_factor" => 1.3960],
            ["name" => "Akbash", "expected_life_id" => 3, "breed_factor" => 1.1909],
            ["name" => "Akita", "expected_life_id" => 4, "breed_factor" => 1.3523],
            ["name" => "Alaskan Husky", "expected_life_id" => 6, "breed_factor" => 1.3100],
            ["name" => "Alaskan Malamute", "expected_life_id" => 5, "breed_factor" => 1.2100],
            ["name" => "American Alaskan Spitz", "expected_life_id" => 6, "breed_factor" => 1.0160],
            ["name" => "American Bandogge Mastiff", "expected_life_id" => 3, "breed_factor" => 2.2482],
            ["name" => "American Black and Tan Coonhound", "expected_life_id" => 4, "breed_factor" => 1.1355],
            ["name" => "American Blue Gascon Hound", "expected_life_id" => 4, "breed_factor" => 1.0488],
            ["name" => "American Bobtail", "expected_life_id" => 9, "breed_factor" => 0.5920],
            ["name" => "American Bulldog", "expected_life_id" => 4, "breed_factor" => 1.5851],
            ["name" => "American Cocker Spaniel", "expected_life_id" => 5, "breed_factor" => 1.3740],
            ["name" => "American Curl", "expected_life_id" => 9, "breed_factor" => 0.6015],
            ["name" => "American English Coonhound", "expected_life_id" => 4, "breed_factor" => 1.1176],
            ["name" => "American Eskimo", "expected_life_id" => 6, "breed_factor" => 0.9842],
            ["name" => "American Eskimo-Miniature", "expected_life_id" => 6, "breed_factor" => 1.0323],
            ["name" => "American Foxhound", "expected_life_id" => 5, "breed_factor" => 1.1000],
            ["name" => "American Hairless Terrier", "expected_life_id" => 8, "breed_factor" => 0.9236],
            ["name" => "American Indian", "expected_life_id" => 9, "breed_factor" => 1.0827],
            ["name" => "American Long Hair", "expected_life_id" => 6, "breed_factor" => 0.6111],
            ["name" => "American Mastiff", "expected_life_id" => 4, "breed_factor" => 2.3957],
            ["name" => "American Mastiff (Panja)", "expected_life_id" => 4, "breed_factor" => 1.3740],
            ["name" => "American Pit Bull", "expected_life_id" => 5, "breed_factor" => 1.1909],
            ["name" => "American Pitbull Terrier", "expected_life_id" => 5, "breed_factor" => 1.3740],
            ["name" => "American Royal Retriever", "expected_life_id" => 5, "breed_factor" => 1.0323],
            ["name" => "American Shorthair", "expected_life_id" => 9, "breed_factor" => 0.5297],
            ["name" => "American Staffordshire Bull Terrier", "expected_life_id" => 5, "breed_factor" => 1.2691],
            ["name" => "American Staffordshire Terrier", "expected_life_id" => 4, "breed_factor" => 1.3310],
            ["name" => "American Staghound", "expected_life_id" => 6, "breed_factor" => 1.0488],
            ["name" => "American Tundra Shepherd", "expected_life_id" => 7, "breed_factor" => 1.0323],
            ["name" => "American Water Spaniel", "expected_life_id" => 4, "breed_factor" => 1.1722],
            ["name" => "American Wirehair", "expected_life_id" => 8, "breed_factor" => 0.5645],
            ["name" => "Anatolian", "expected_life_id" => 6, "breed_factor" => 0.5645],
            ["name" => "Anatolian Shepherd", "expected_life_id" => 6, "breed_factor" => 1.6891],
            ["name" => "Angora", "expected_life_id" => 8, "breed_factor" => 0.5556],
            ["name" => "Appenzeller Sennenhunde", "expected_life_id" => 5, "breed_factor" => 1.1000],
            ["name" => "Argentine Dogo", "expected_life_id" => 4, "breed_factor" => 1.3523],
            ["name" => "Australian Cattle Dog", "expected_life_id" => 6, "breed_factor" => 1.1176],
            ["name" => "Australian Dingo", "expected_life_id" => 8, "breed_factor" => 1.0323],
            ["name" => "Australian Kelpie", "expected_life_id" => 5, "breed_factor" => 1.1722],
            ["name" => "Australian Shepherd", "expected_life_id" => 8, "breed_factor" => 0.9384],
            ["name" => "Australian Shepherd-Miniature", "expected_life_id" => 5, "breed_factor" => 0.9842],
            ["name" => "Australian Silky Terrier", "expected_life_id" => 8, "breed_factor" => 1.0000],
            ["name" => "Australian Stumpy Tail Cattle", "expected_life_id" => 5, "breed_factor" => 0.9687],
            ["name" => "Australian Terrier", "expected_life_id" => 8, "breed_factor" => 0.8134],
            ["name" => "Azawakh Hound", "expected_life_id" => 5, "breed_factor" => 1.2100],
            ["name" => "Balinese", "expected_life_id" => 6, "breed_factor" => 0.5920],
            ["name" => "Barbet", "expected_life_id" => 7, "breed_factor" => 0.8807],
            ["name" => "Basenji", "expected_life_id" => 6, "breed_factor" => 0.9091],
            ["name" => "Basset Fauve de Bretagne", "expected_life_id" => 5, "breed_factor" => 1.1176],
            ["name" => "Basset Hound", "expected_life_id" => 4, "breed_factor" => 1.5114],
            ["name" => "Bavarian Mountain Hound", "expected_life_id" => 5, "breed_factor" => 0.9384],
            ["name" => "Beagle", "expected_life_id" => 6, "breed_factor" => 1.2294],
            ["name" => "Bearded Collie", "expected_life_id" => 8, "breed_factor" => 1.1909],
            ["name" => "Beauceron", "expected_life_id" => 5, "breed_factor" => 1.0656],
            ["name" => "Bedlington Terrier", "expected_life_id" => 6, "breed_factor" => 1.0160],
            ["name" => "Belgian Laekenois", "expected_life_id" => 6, "breed_factor" => 1.0323],
            ["name" => "Belgian Malinois", "expected_life_id" => 5, "breed_factor" => 0.9535],
            ["name" => "Belgian Mastiff", "expected_life_id" => 3, "breed_factor" => 2.2842],
            ["name" => "Belgian Sheepdog", "expected_life_id" => 5, "breed_factor" => 1.1355],
            ["name" => "Belgian Shepherd", "expected_life_id" => 5, "breed_factor" => 1.2100],
            ["name" => "Belgian Tervuren", "expected_life_id" => 5, "breed_factor" => 1.0160],
            ["name" => "Bengal", "expected_life_id" => 6, "breed_factor" => 0.5827],
            ["name" => "Bergamasco Sheepdog", "expected_life_id" => 7, "breed_factor" => 1.0656],
            ["name" => "Berger Des Pyrénées", "expected_life_id" => 5, "breed_factor" => 1.0488],
            ["name" => "Berger Picard/Picardy Sheepdog", "expected_life_id" => 6, "breed_factor" => 1.0488],
            ["name" => "Bernese Mountain Dog", "expected_life_id" => 1, "breed_factor" => 2.0438],
            ["name" => "Bichon Frise", "expected_life_id" => 7, "breed_factor" => 0.8948],
            ["name" => "Birman", "expected_life_id" => 6, "breed_factor" => 0.6209],
            ["name" => "Black and Tan Coonhound", "expected_life_id" => 4, "breed_factor" => 1.0488],
            ["name" => "Black Russian Terrier", "expected_life_id" => 5, "breed_factor" => 1.8287],
            ["name" => "Blackmouth Cur", "expected_life_id" => 5, "breed_factor" => 1.2100],
            ["name" => "Bloodhound", "expected_life_id" => 2, "breed_factor" => 1.4410],
            ["name" => "Blue Heeler", "expected_life_id" => 6, "breed_factor" => 0.9842],
            ["name" => "Blue Picardy Spaniel", "expected_life_id" => 6, "breed_factor" => 0.9384],
            ["name" => "Blue Tick Coonhound", "expected_life_id" => 4, "breed_factor" => 1.2100],
            ["name" => "Boerboel", "expected_life_id" => 1, "breed_factor" => 2.2842],
            ["name" => "Bolognese", "expected_life_id" => 7, "breed_factor" => 0.8807],
            ["name" => "Bombay", "expected_life_id" => 10, "breed_factor" => 0.6111],
            ["name" => "Border Collie", "expected_life_id" => 5, "breed_factor" => 0.9535],
            ["name" => "Border Terrier", "expected_life_id" => 6, "breed_factor" => 0.8948],
            ["name" => "Borzoi/Russian Wolfhound", "expected_life_id" => 4, "breed_factor" => 1.2100],
            ["name" => "Boston Terrier", "expected_life_id" => 5, "breed_factor" => 0.9384],
            ["name" => "Bouvier des Flandres", "expected_life_id" => 4, "breed_factor" => 1.5601],
            ["name" => "Boxer", "expected_life_id" => 3, "breed_factor" => 1.5356],
            ["name" => "Boykin Spaniel", "expected_life_id" => 6, "breed_factor" => 1.2491],
            ["name" => "Bracco Italiano", "expected_life_id" => 5, "breed_factor" => 1.0323],
            ["name" => "Brazilian Fila", "expected_life_id" => 3, "breed_factor" => 1.0323],
            ["name" => "Briard", "expected_life_id" => 4, "breed_factor" => 1.1909],
            ["name" => "British Longhair", "expected_life_id" => 6, "breed_factor" => 0.5645],
            ["name" => "British Shorthair", "expected_life_id" => 10, "breed_factor" => 0.5827],
            ["name" => "Brittany", "expected_life_id" => 6, "breed_factor" => 1.1176],
            ["name" => "Brussels Griffon", "expected_life_id" => 6, "breed_factor" => 0.8531],
            ["name" => "Bull Boxer", "expected_life_id" => 3, "breed_factor" => 1.4875],
            ["name" => "Bull Terrier", "expected_life_id" => 5, "breed_factor" => 1.4410],
            ["name" => "Bull Terrier-Miniature", "expected_life_id" => 5, "breed_factor" => 1.1722],
            ["name" => "Bulldog", "expected_life_id" => 3, "breed_factor" => 1.5356],
            ["name" => "Bullmastiff", "expected_life_id" => 2, "breed_factor" => 2.3957],
            ["name" => "Bullseye", "expected_life_id" => 6, "breed_factor" => 0.5645],
            ["name" => "Burmese", "expected_life_id" => 12, "breed_factor" => 0.5920],
            ["name" => "Cairn Terrier", "expected_life_id" => 6, "breed_factor" => 0.8948],
            ["name" => "California Spangled", "expected_life_id" => 5, "breed_factor" => 0.5735],
            ["name" => "Canaan Dog", "expected_life_id" => 4, "breed_factor" => 1.1722],
            ["name" => "Canadian Eskimo/Inuit", "expected_life_id" => 5, "breed_factor" => 0.9535],
            ["name" => "Canary Dog", "expected_life_id" => 5, "breed_factor" => 1.1000],
            ["name" => "Cane Corso", "expected_life_id" => 3, "breed_factor" => 2.1436],
            ["name" => "Cardigan Welsh Corgi", "expected_life_id" => 6, "breed_factor" => 1.1537],
            ["name" => "Catahoula Leopard Dog", "expected_life_id" => 5, "breed_factor" => 1.1537],
            ["name" => "Caucasian Ovcharka", "expected_life_id" => 3, "breed_factor" => 1.7162],
            ["name" => "Cavalier King Charles Spaniel", "expected_life_id" => 4, "breed_factor" => 1.0827],
            ["name" => "Central Asian Shepherd", "expected_life_id" => 6, "breed_factor" => 1.7999],
            ["name" => "Cesky Terrier", "expected_life_id" => 5, "breed_factor" => 1.0656],
            ["name" => "Chanille", "expected_life_id" => 5, "breed_factor" => 1.0323],
            ["name" => "Chartreux", "expected_life_id" => 6, "breed_factor" => 0.6209],
            ["name" => "Chausie", "expected_life_id" => 7, "breed_factor" => 0.5645],
            ["name" => "Chesapeake Bay Retriever", "expected_life_id" => 4, "breed_factor" => 1.4183],
            ["name" => "Chihuahua", "expected_life_id" => 6, "breed_factor" => 0.6209],
            ["name" => "Chihuahua-Long-Haired", "expected_life_id" => 6, "breed_factor" => 1.1176],
            ["name" => "Chinchilla Persian", "expected_life_id" => 10, "breed_factor" => 0.6309],
            ["name" => "Chinese Crested", "expected_life_id" => 5, "breed_factor" => 0.8668],
            ["name" => "Chinese Crested Powder Puff", "expected_life_id" => 5, "breed_factor" => 1.1537],
            ["name" => "Chinese Pug", "expected_life_id" => 6, "breed_factor" => 1.2691],
            ["name" => "Chinook", "expected_life_id" => 5, "breed_factor" => 1.1000],
            ["name" => "Chipom", "expected_life_id" => 6, "breed_factor" => 0.8948],
            ["name" => "Chipoo", "expected_life_id" => 7, "breed_factor" => 0.7880],
            ["name" => "Chow Chow", "expected_life_id" => 4, "breed_factor" => 1.1176],
            ["name" => "Cirneco dell Etna", "expected_life_id" => 6, "breed_factor" => 1.0323],
            ["name" => "Clumber Spaniel", "expected_life_id" => 6, "breed_factor" => 1.3740],
            ["name" => "Cockapoo", "expected_life_id" => 6, "breed_factor" => 0.7633],
            ["name" => "Cocker Spaniel", "expected_life_id" => 5, "breed_factor" => 0.9842],
            ["name" => "Cocker Spaniel-Miniature", "expected_life_id" => 5, "breed_factor" => 1.0827],
            ["name" => "Collie", "expected_life_id" => 4, "breed_factor" => 1.2691],
            ["name" => "Collie - Smooth Coated", "expected_life_id" => 4, "breed_factor" => 1.0160],
            ["name" => "Colorpoint Shorthair", "expected_life_id" => 8, "breed_factor" => 0.5735],
            ["name" => "Coonhound", "expected_life_id" => 5, "breed_factor" => 1.0488],
            ["name" => "Coonhound-Black & Tan", "expected_life_id" => 4, "breed_factor" => 1.0000],
            ["name" => "Coonhound-Blue Tick", "expected_life_id" => 4, "breed_factor" => 1.1722],
            ["name" => "Coonhound-Redbone", "expected_life_id" => 6, "breed_factor" => 1.1000],
            ["name" => "Cornish Rex", "expected_life_id" => 9, "breed_factor" => 0.6830],
            ["name" => "Coton de Tulear", "expected_life_id" => 7, "breed_factor" => 0.7756],
            ["name" => "Curly-Coated Retriever", "expected_life_id" => 4, "breed_factor" => 1.1909],
            ["name" => "Cymric", "expected_life_id" => 4, "breed_factor" => 0.5645],
            ["name" => "Czechoslovakian Wolfdog", "expected_life_id" => 4, "breed_factor" => 1.0656],
            ["name" => "Dachshund", "expected_life_id" => 6, "breed_factor" => 1.0000],
            ["name" => "Dachshund-Long Haired", "expected_life_id" => 6, "breed_factor" => 1.1176],
            ["name" => "Dachshund-Miniature", "expected_life_id" => 6, "breed_factor" => 1.0827],
            ["name" => "Dachshund-Miniature Long Haired", "expected_life_id" => 6, "breed_factor" => 1.1176],
            ["name" => "Dachshund-Miniature Smooth Haired", "expected_life_id" => 6, "breed_factor" => 1.0827],
            ["name" => "Dachshund-Miniature Wire Hair", "expected_life_id" => 6, "breed_factor" => 1.1909],
            ["name" => "Dachshund-Wire Haired", "expected_life_id" => 6, "breed_factor" => 1.1537],
            ["name" => "Dalmatian", "expected_life_id" => 6, "breed_factor" => 1.4641],
            ["name" => "Dandie Dinmont Terrier", "expected_life_id" => 5, "breed_factor" => 1.0160],
            ["name" => "Deerhound", "expected_life_id" => 1, "breed_factor" => 0.9384],
            ["name" => "Designer / Hybrid", "expected_life_id" => 5, "breed_factor" => 1.0488],
            ["name" => "Devon Rex", "expected_life_id" => 5, "breed_factor" => 0.6410],
            ["name" => "Dingo/Carolina", "expected_life_id" => 6, "breed_factor" => 1.1537],
            ["name" => "Doberman Pinscher", "expected_life_id" => 5, "breed_factor" => 1.9487],
            ["name" => "Dogue de Bordeaux", "expected_life_id" => 2, "breed_factor" => 2.3579],
            ["name" => "Domestic Longhair", "expected_life_id" => 7, "breed_factor" => 0.5214],
            ["name" => "Domestic Mediumhair", "expected_life_id" => 7, "breed_factor" => 0.5214],
            ["name" => "Domestic Shorthair", "expected_life_id" => 7, "breed_factor" => 0.5214],
            ["name" => "Donskoy", "expected_life_id" => 6, "breed_factor" => 0.5827],
            ["name" => "Drever", "expected_life_id" => 6, "breed_factor" => 0.9384],
            ["name" => "Dunker/Norwegian Hound", "expected_life_id" => 6, "breed_factor" => 0.9384],
            ["name" => "Dutch Sheepdog", "expected_life_id" => 6, "breed_factor" => 1.1722],
            ["name" => "Egyptian Mau", "expected_life_id" => 7, "breed_factor" => 0.5735],
            ["name" => "English Bull", "expected_life_id" => 3, "breed_factor" => 1.5114],
            ["name" => "English Bulldog", "expected_life_id" => 3, "breed_factor" => 2.2128],
            ["name" => "English Cocker Spaniel", "expected_life_id" => 6, "breed_factor" => 1.1176],
            ["name" => "English Foxhound", "expected_life_id" => 4, "breed_factor" => 0.9535],
            ["name" => "English Mastiff", "expected_life_id" => 3, "breed_factor" => 1.4875],
            ["name" => "English Pointer", "expected_life_id" => 7, "breed_factor" => 1.2491],
            ["name" => "English Setter", "expected_life_id" => 5, "breed_factor" => 1.1000],
            ["name" => "English Shepherd", "expected_life_id" => 7, "breed_factor" => 1.0323],
            ["name" => "English Springer Spaniel", "expected_life_id" => 5, "breed_factor" => 1.1176],
            ["name" => "English Toy Spaniel", "expected_life_id" => 4, "breed_factor" => 0.8006],
            ["name" => "English Toy Terrier", "expected_life_id" => 6, "breed_factor" => 0.9384],
            ["name" => "Entlebucher Mountain Dog", "expected_life_id" => 5, "breed_factor" => 1.2691],
            ["name" => "Estrela Mountain Dog", "expected_life_id" => 4, "breed_factor" => 1.1909],
            ["name" => "Eurasian/Eurasier", "expected_life_id" => 5, "breed_factor" => 1.1000],
            ["name" => "Exotic Longhair", "expected_life_id" => 6, "breed_factor" => 0.5556],
            ["name" => "Exotic Shorthair", "expected_life_id" => 6, "breed_factor" => 0.6015],
            ["name" => "Field Spaniel", "expected_life_id" => 4, "breed_factor" => 1.1537],
            ["name" => "Fila Brasileiro/Brazillian Mastiff", "expected_life_id" => 3, "breed_factor" => 2.2842],
            ["name" => "Finnish Hound", "expected_life_id" => 4, "breed_factor" => 1.0323],
            ["name" => "Finnish Lapphund", "expected_life_id" => 6, "breed_factor" => 1.1537],
            ["name" => "Finnish Spitz", "expected_life_id" => 6, "breed_factor" => 1.0323],
            ["name" => "Flat-Coated Retriever", "expected_life_id" => 3, "breed_factor" => 1.2691],
            ["name" => "Formosan (Taiwanese) Mountain Dog", "expected_life_id" => 4, "breed_factor" => 0.9236],
            ["name" => "Fourche Terrier", "expected_life_id" => 7, "breed_factor" => 1.0323],
            ["name" => "Fox Terrier", "expected_life_id" => 6, "breed_factor" => 0.9687],
            ["name" => "French Bulldog", "expected_life_id" => 5, "breed_factor" => 2.2128],
            ["name" => "French Mastiff", "expected_life_id" => 2, "breed_factor" => 1.5601],
            ["name" => "French Spaniel", "expected_life_id" => 5, "breed_factor" => 0.9091],
            ["name" => "Ganaraskan", "expected_life_id" => 6, "breed_factor" => 1.0000],
            ["name" => "Gascogne Braque Francais", "expected_life_id" => 4, "breed_factor" => 0.9384],
            ["name" => "German Pinscher", "expected_life_id" => 6, "breed_factor" => 1.0656],
            ["name" => "German Pointer", "expected_life_id" => 6, "breed_factor" => 1.0323],
            ["name" => "German Shepherd", "expected_life_id" => 4, "breed_factor" => 1.3100],
            ["name" => "German Spitz", "expected_life_id" => 6, "breed_factor" => 0.9091],
            ["name" => "German Wirehaired Pointer", "expected_life_id" => 5, "breed_factor" => 1.1000],
            ["name" => "German/Mittel Spitz", "expected_life_id" => 7, "breed_factor" => 0.9384],
            ["name" => "Giant Schnauzer", "expected_life_id" => 5, "breed_factor" => 1.2491],
            ["name" => "Glen of Imaal Terrier", "expected_life_id" => 5, "breed_factor" => 1.2100],
            ["name" => "Golden Retriever", "expected_life_id" => 5, "breed_factor" => 1.3523],
            ["name" => "Goldendoodle", "expected_life_id" => 6, "breed_factor" => 1.0000],
            ["name" => "Gordon Setter", "expected_life_id" => 4, "breed_factor" => 1.2691],
            ["name" => "Grand Basset Griffon Vendéen", "expected_life_id" => 5, "breed_factor" => 0.9687],
            ["name" => "Great Dane", "expected_life_id" => 1, "breed_factor" => 2.0766],
            ["name" => "Great Pyrenees", "expected_life_id" => 4, "breed_factor" => 1.4183],
            ["name" => "Greater Swiss Mountain Dog", "expected_life_id" => 4, "breed_factor" => 1.9487],
            ["name" => "Greenland Dog", "expected_life_id" => 6, "breed_factor" => 0.9384],
            ["name" => "Greyhound", "expected_life_id" => 4, "breed_factor" => 1.3310],
            ["name" => "Groenendael Belgian Shepherd", "expected_life_id" => 4, "breed_factor" => 1.0160],
            ["name" => "Hamiltonstovare", "expected_life_id" => 5, "breed_factor" => 0.9384],
            ["name" => "Harrier", "expected_life_id" => 6, "breed_factor" => 1.1537],
            ["name" => "Havana Brown", "expected_life_id" => 10, "breed_factor" => 0.5920],
            ["name" => "Havanese", "expected_life_id" => 7, "breed_factor" => 0.7756],
            ["name" => "Himalayan", "expected_life_id" => 7, "breed_factor" => 0.5735],
            ["name" => "Hovawart", "expected_life_id" => 5, "breed_factor" => 1.2100],
            ["name" => "Hungarian Sheepdog", "expected_life_id" => 3, "breed_factor" => 1.2100],
            ["name" => "Ibizan Hound", "expected_life_id" => 4, "breed_factor" => 1.0656],
            ["name" => "Icelandic Sheepdog", "expected_life_id" => 6, "breed_factor" => 1.0323],
            ["name" => "Inca Orchid", "expected_life_id" => 4, "breed_factor" => 1.0323],
            ["name" => "Irish Setter", "expected_life_id" => 6, "breed_factor" => 1.1537],
            ["name" => "Irish Terrier", "expected_life_id" => 7, "breed_factor" => 1.1176],
            ["name" => "Irish Water Spaniel", "expected_life_id" => 4, "breed_factor" => 1.1537],
            ["name" => "Irish Wolfhound", "expected_life_id" => 2, "breed_factor" => 2.0438],
            ["name" => "Italian Bulldogge", "expected_life_id" => 3, "breed_factor" => 1.2894],
            ["name" => "Italian Greyhound", "expected_life_id" => 8, "breed_factor" => 1.1000],
            ["name" => "Jack Russell Terrier", "expected_life_id" => 7, "breed_factor" => 0.7395],
            ["name" => "Japanese Bobtail", "expected_life_id" => 8, "breed_factor" => 0.5920],
            ["name" => "Japanese Chin", "expected_life_id" => 3, "breed_factor" => 0.8134],
            ["name" => "Japanese Spaniel", "expected_life_id" => 3, "breed_factor" => 1.0323],
            ["name" => "Japanese Spitz", "expected_life_id" => 5, "breed_factor" => 0.9842],
            ["name" => "Japanese Terrier", "expected_life_id" => 5, "breed_factor" => 0.9535],
            ["name" => "Javanese", "expected_life_id" => 5, "breed_factor" => 0.5920],
            ["name" => "Jindo", "expected_life_id" => 6, "breed_factor" => 1.2100],
            ["name" => "Kai Ken", "expected_life_id" => 5, "breed_factor" => 1.1537],
            ["name" => "Karelian Bear Dog", "expected_life_id" => 4, "breed_factor" => 1.3960],
            ["name" => "Keeshond", "expected_life_id" => 6, "breed_factor" => 1.1176],
            ["name" => "Kelpie", "expected_life_id" => 5, "breed_factor" => 1.0323],
            ["name" => "Kerry Blue Terrier", "expected_life_id" => 6, "breed_factor" => 1.1722],
            ["name" => "Kishu Ken", "expected_life_id" => 5, "breed_factor" => 1.1722],
            ["name" => "Komondor", "expected_life_id" => 3, "breed_factor" => 1.1909],
            ["name" => "Kooikerhondje", "expected_life_id" => 5, "breed_factor" => 1.0323],
            ["name" => "Korat", "expected_life_id" => 6, "breed_factor" => 0.5556],
            ["name" => "Kuvasz", "expected_life_id" => 4, "breed_factor" => 1.6625],
            ["name" => "Kyi-Leo", "expected_life_id" => 6, "breed_factor" => 1.0488],
            ["name" => "Labradoodle", "expected_life_id" => 5, "breed_factor" => 0.9687],
            ["name" => "Labrador Retriever", "expected_life_id" => 5, "breed_factor" => 1.3310],
            ["name" => "Laekenois Belgian Shepherd", "expected_life_id" => 4, "breed_factor" => 1.1000],
            ["name" => "Lagotto Romagnolo", "expected_life_id" => 6, "breed_factor" => 1.2294],
            ["name" => "Lakeland Terrier", "expected_life_id" => 7, "breed_factor" => 1.1000],
            ["name" => "Lancashire Heeler", "expected_life_id" => 6, "breed_factor" => 1.0323],
            ["name" => "Landseer", "expected_life_id" => 4, "breed_factor" => 1.0827],
            ["name" => "LaPerm", "expected_life_id" => 7, "breed_factor" => 0.5735],
            ["name" => "Large Munsterlander", "expected_life_id" => 5, "breed_factor" => 0.9236],
            ["name" => "Leonberger", "expected_life_id" => 3, "breed_factor" => 1.9180],
            ["name" => "Lhasa Apso", "expected_life_id" => 6, "breed_factor" => 0.8668],
            ["name" => "Llewellin Setter", "expected_life_id" => 5, "breed_factor" => 1.4183],
            ["name" => "Louisiana Catahoula Hog Dog", "expected_life_id" => 5, "breed_factor" => 1.0488],
            ["name" => "Lowchen", "expected_life_id" => 6, "breed_factor" => 0.8264],
            ["name" => "Maine Coon", "expected_life_id" => 6, "breed_factor" => 0.6722],
            ["name" => "Malamute Husky", "expected_life_id" => 5, "breed_factor" => 1.0160],
            ["name" => "Malinois Belgian Shepherd", "expected_life_id" => 5, "breed_factor" => 1.2691],
            ["name" => "Maltese", "expected_life_id" => 7, "breed_factor" => 0.8134],
            ["name" => "Maltipoo", "expected_life_id" => 7, "breed_factor" => 0.7278],
            ["name" => "Manchester Terrier", "expected_life_id" => 7, "breed_factor" => 1.0656],
            ["name" => "Manx", "expected_life_id" => 4, "breed_factor" => 0.5556],
            ["name" => "Manx Longhair", "expected_life_id" => 4, "breed_factor" => 0.5468],
            ["name" => "Maremma", "expected_life_id" => 5, "breed_factor" => 1.3740],
            ["name" => "Mastiff", "expected_life_id" => 3, "breed_factor" => 2.4341],
            ["name" => "Mexican Hairless", "expected_life_id" => 9, "breed_factor" => 1.0000],
            ["name" => "Mexican Hairless-Crested", "expected_life_id" => 6, "breed_factor" => 1.2100],
            ["name" => "Mi-Ki", "expected_life_id" => 3, "breed_factor" => 0.9687],
            ["name" => "Miniature Australian Shepherd", "expected_life_id" => 5, "breed_factor" => 0.9091],
            ["name" => "Miniature Bull Terrier", "expected_life_id" => 5, "breed_factor" => 1.1000],
            ["name" => "Miniature Dachshund", "expected_life_id" => 6, "breed_factor" => 0.8948],
            ["name" => "Miniature Pinscher", "expected_life_id" => 7, "breed_factor" => 1.0000],
            ["name" => "Miniature Poodle", "expected_life_id" => 8, "breed_factor" => 0.8397],
            ["name" => "Miniature Schnauzer", "expected_life_id" => 7, "breed_factor" => 0.9091],
            ["name" => "Mixed Breed - Cat", "expected_life_id" => 8, "breed_factor" => 0.5214],
            ["name" => "Mixed Breed - Dog", "expected_life_id" => 4, "breed_factor" => 0.8668],
            ["name" => "Mountain Cur", "expected_life_id" => 7, "breed_factor" => 1.1000],
            ["name" => "Mountain Terrier", "expected_life_id" => 5, "breed_factor" => 0.9384],
            ["name" => "Mudi", "expected_life_id" => 6, "breed_factor" => 1.0488],
            ["name" => "Munchkin", "expected_life_id" => 6, "breed_factor" => 0.5468],
            ["name" => "Münsterländer", "expected_life_id" => 6, "breed_factor" => 1.0488],
            ["name" => "Native American Indian", "expected_life_id" => 9, "breed_factor" => 0.9842],
            ["name" => "Neapolitan Mastiff", "expected_life_id" => 3, "breed_factor" => 2.3957],
            ["name" => "Nebelung", "expected_life_id" => 10, "breed_factor" => 0.5920],
            ["name" => "Nebolish Mastiff", "expected_life_id" => 5, "breed_factor" => 2.2842],
            ["name" => "New Zealand Huntaway", "expected_life_id" => 6, "breed_factor" => 0.9384],
            ["name" => "New Zealand Sheepdog", "expected_life_id" => 6, "breed_factor" => 1.0323],
            ["name" => "Newfoundland", "expected_life_id" => 3, "breed_factor" => 2.3579],
            ["name" => "Norfolk Terrier", "expected_life_id" => 6, "breed_factor" => 0.9091],
            ["name" => "Norrbottenspets", "expected_life_id" => 6, "breed_factor" => 0.9535],
            ["name" => "Norwegian Buhund", "expected_life_id" => 6, "breed_factor" => 1.1722],
            ["name" => "Norwegian Elkhound", "expected_life_id" => 4, "breed_factor" => 1.1176],
            ["name" => "Norwegian Forest", "expected_life_id" => 5, "breed_factor" => 0.5382],
            ["name" => "Norwegian Viking Buhund", "expected_life_id" => 6, "breed_factor" => 1.0323],
            ["name" => "Norwegian/Norsk Lundehund", "expected_life_id" => 5, "breed_factor" => 1.0827],
            ["name" => "Norwich Terrier", "expected_life_id" => 6, "breed_factor" => 0.8397],
            ["name" => "Nova Scotia Duck Tolling Retriever", "expected_life_id" => 6, "breed_factor" => 1.1537],
            ["name" => "Ocicat", "expected_life_id" => 5, "breed_factor" => 0.5920],
            ["name" => "Ojos Azules", "expected_life_id" => 4, "breed_factor" => 0.5735],
            ["name" => "Old Boston Bulldogge", "expected_life_id" => 5, "breed_factor" => 0.9384],
            ["name" => "Old English Mastiff", "expected_life_id" => 3, "breed_factor" => 1.4183],
            ["name" => "Old English Sheepdog", "expected_life_id" => 5, "breed_factor" => 1.1355],
            ["name" => "Old Victorian Bulldogge", "expected_life_id" => 5, "breed_factor" => 0.9842],
            ["name" => "Olde English Bulldog", "expected_life_id" => 4, "breed_factor" => 1.4410],
            ["name" => "Oriental", "expected_life_id" => 10, "breed_factor" => 0.6111],
            ["name" => "Otterhound", "expected_life_id" => 4, "breed_factor" => 1.2294],
            ["name" => "Papillon", "expected_life_id" => 7, "breed_factor" => 0.8134],
            ["name" => "Parson Russell Terrier", "expected_life_id" => 7, "breed_factor" => 1.0160],
            ["name" => "Patterdale/Fell Terrier", "expected_life_id" => 5, "breed_factor" => 0.8006],
            ["name" => "Pekingese", "expected_life_id" => 7, "breed_factor" => 0.7164],
            ["name" => "Pembroke Welsh Corgi", "expected_life_id" => 5, "breed_factor" => 1.0488],
            ["name" => "Perro de Presa Canario", "expected_life_id" => 5, "breed_factor" => 1.3740],
            ["name" => "Persian", "expected_life_id" => 10, "breed_factor" => 0.6512],
            ["name" => "Persian-Himalayan", "expected_life_id" => 7, "breed_factor" => 0.5735],
            ["name" => "Peruvian Hairless", "expected_life_id" => 4, "breed_factor" => 1.0323],
            ["name" => "Peruvian Inca Orchid", "expected_life_id" => 4, "breed_factor" => 1.0323],
            ["name" => "Peterbald", "expected_life_id" => 4, "breed_factor" => 0.5735],
            ["name" => "Petit Basset Griffon Vendeen", "expected_life_id" => 5, "breed_factor" => 1.2491],
            ["name" => "Pharaoh Hound", "expected_life_id" => 5, "breed_factor" => 1.0323],
            ["name" => "Picardy Spaniel", "expected_life_id" => 6, "breed_factor" => 0.9384],
            ["name" => "Pitbull", "expected_life_id" => 5, "breed_factor" => 1.3100],
            ["name" => "Pixiebob", "expected_life_id" => 5, "breed_factor" => 0.5645],
            ["name" => "Plott", "expected_life_id" => 6, "breed_factor" => 1.0488],
            ["name" => "Pointer", "expected_life_id" => 7, "breed_factor" => 1.2294],
            ["name" => "Polish Lowland Sheepdog", "expected_life_id" => 5, "breed_factor" => 1.3523],
            ["name" => "Polish Tatra", "expected_life_id" => 5, "breed_factor" => 1.1000],
            ["name" => "Polski Ocharch Nizinny", "expected_life_id" => 5, "breed_factor" => 1.0488],
            ["name" => "Pomapoo", "expected_life_id" => 6, "breed_factor" => 0.8397],
            ["name" => "Pomeranian", "expected_life_id" => 6, "breed_factor" => 0.8807],
            ["name" => "Poodle", "expected_life_id" => 5, "breed_factor" => 1.1000],
            ["name" => "Poodle-Standard", "expected_life_id" => 5, "breed_factor" => 1.1537],
            ["name" => "Poodle-Teacup", "expected_life_id" => 6, "breed_factor" => 1.2100],
            ["name" => "Poodle-Toy", "expected_life_id" => 8, "breed_factor" => 1.2294],
            ["name" => "Porkie", "expected_life_id" => 6, "breed_factor" => 0.9535],
            ["name" => "Portuguese Podengo", "expected_life_id" => 8, "breed_factor" => 1.1537],
            ["name" => "Portuguese Podenjo Pequeno", "expected_life_id" => 8, "breed_factor" => 1.0656],
            ["name" => "Portuguese Pointer", "expected_life_id" => 6, "breed_factor" => 1.2294],
            ["name" => "Portuguese Water Dog", "expected_life_id" => 6, "breed_factor" => 1.0160],
            ["name" => "Prague Ratter", "expected_life_id" => 6, "breed_factor" => 0.8006],
            ["name" => "Pudelpointer", "expected_life_id" => 5, "breed_factor" => 0.9842],
            ["name" => "Pug", "expected_life_id" => 6, "breed_factor" => 1.1537],
            ["name" => "Puggle", "expected_life_id" => 7, "breed_factor" => 0.9535],
            ["name" => "Puli", "expected_life_id" => 5, "breed_factor" => 1.0160],
            ["name" => "Pumi", "expected_life_id" => 5, "breed_factor" => 1.0323],
            ["name" => "Pyrenean Mastiff", "expected_life_id" => 2, "breed_factor" => 2.2842],
            ["name" => "Pyrenean Mountain Dog (Great Pyrenees)", "expected_life_id" => 4, "breed_factor" => 1.2894],
            ["name" => "Pyrenean Sheepdog", "expected_life_id" => 5, "breed_factor" => 1.0323],
            ["name" => "Pyrenean Shepherd", "expected_life_id" => 5, "breed_factor" => 1.0323],
            ["name" => "Pyrenees Braque Francais", "expected_life_id" => 6, "breed_factor" => 0.9842],
            ["name" => "Queensland Heeler", "expected_life_id" => 6, "breed_factor" => 1.2894],
            ["name" => "Rafeiro do Alentejo", "expected_life_id" => 5, "breed_factor" => 1.7716],
            ["name" => "Ragdoll", "expected_life_id" => 5, "breed_factor" => 0.5827],
            ["name" => "Rare Breed", "expected_life_id" => 5, "breed_factor" => 1.2691],
            ["name" => "Rat Terrier", "expected_life_id" => 7, "breed_factor" => 0.9687],
            ["name" => "Redbone Coonhound", "expected_life_id" => 6, "breed_factor" => 1.1537],
            ["name" => "Rex", "expected_life_id" => 6, "breed_factor" => 0.5920],
            ["name" => "Rhodesian Ridgeback", "expected_life_id" => 3, "breed_factor" => 1.3523],
            ["name" => "Roman Rottweiler", "expected_life_id" => 4, "breed_factor" => 1.3523],
            ["name" => "Rottweiler", "expected_life_id" => 1, "breed_factor" => 2.1779],
            ["name" => "Russian Blue", "expected_life_id" => 10, "breed_factor" => 0.5297],
            ["name" => "Russian Bolonka", "expected_life_id" => 7, "breed_factor" => 0.9384],
            ["name" => "Russian Hound", "expected_life_id" => 4, "breed_factor" => 1.0488],
            ["name" => "Russian Toy", "expected_life_id" => 5, "breed_factor" => 1.0323],
            ["name" => "Russian Wolfhound", "expected_life_id" => 4, "breed_factor" => 1.0827],
            ["name" => "Saint Bernard", "expected_life_id" => 1, "breed_factor" => 2.5126],
            ["name" => "Saluki (Gazelle Hound)", "expected_life_id" => 4, "breed_factor" => 1.1537],
            ["name" => "Samoyed", "expected_life_id" => 6, "breed_factor" => 1.1355],
            ["name" => "Savannah", "expected_life_id" => 10, "breed_factor" => 0.7051],
            ["name" => "Schapendoes", "expected_life_id" => 7, "breed_factor" => 1.0323],
            ["name" => "Schipperke", "expected_life_id" => 10, "breed_factor" => 1.1000],
            ["name" => "Schnauzer-Giant", "expected_life_id" => 5, "breed_factor" => 1.1537],
            ["name" => "Schnauzer-Miniature", "expected_life_id" => 7, "breed_factor" => 0.9687],
            ["name" => "Schnauzer-Standard", "expected_life_id" => 6, "breed_factor" => 1.1537],
            ["name" => "Schnoodle", "expected_life_id" => 6, "breed_factor" => 0.8807],
            ["name" => "Scottish Deerhound", "expected_life_id" => 2, "breed_factor" => 1.2100],
            ["name" => "Scottish Fold", "expected_life_id" => 8, "breed_factor" => 0.5827],
            ["name" => "Scottish Terrier", "expected_life_id" => 6, "breed_factor" => 1.1355],
            ["name" => "Sealyham Terrier", "expected_life_id" => 6, "breed_factor" => 1.0488],
            ["name" => "Segugio Italiano", "expected_life_id" => 5, "breed_factor" => 0.9384],
            ["name" => "Selkirk Rex", "expected_life_id" => 7, "breed_factor" => 0.6015],
            ["name" => "Serengeti", "expected_life_id" => 3, "breed_factor" => 0.5645],
            ["name" => "Shar Pei", "expected_life_id" => 2, "breed_factor" => 1.5601],
            ["name" => "Sheltie", "expected_life_id" => 6, "breed_factor" => 1.0827],
            ["name" => "Shetland Sheepdog", "expected_life_id" => 6, "breed_factor" => 0.9687],
            ["name" => "Shiba Inu", "expected_life_id" => 7, "breed_factor" => 0.8397],
            ["name" => "Shih Tzu", "expected_life_id" => 5, "breed_factor" => 0.6512],
            ["name" => "Shikoku", "expected_life_id" => 4, "breed_factor" => 0.9384],
            ["name" => "Shiloh Shepherd", "expected_life_id" => 6, "breed_factor" => 1.5356],
            ["name" => "Shorthair Chinchilla", "expected_life_id" => 10, "breed_factor" => 0.5827],
            ["name" => "Siamese", "expected_life_id" => 11, "breed_factor" => 0.5735],
            ["name" => "Siberian", "expected_life_id" => 6, "breed_factor" => 0.5735],
            ["name" => "Siberian Husky", "expected_life_id" => 5, "breed_factor" => 1.0000],
            ["name" => "Silken Windhound", "expected_life_id" => 9, "breed_factor" => 0.9535],
            ["name" => "Silky Terrier", "expected_life_id" => 7, "breed_factor" => 0.7880],
            ["name" => "Singapura", "expected_life_id" => 7, "breed_factor" => 0.5920],
            ["name" => "Skye Terrier", "expected_life_id" => 6, "breed_factor" => 1.0827],
            ["name" => "Sloughi", "expected_life_id" => 5, "breed_factor" => 1.0656],
            ["name" => "Slovensky Cuvac", "expected_life_id" => 5, "breed_factor" => 1.0323],
            ["name" => "Small Munsterlander", "expected_life_id" => 7, "breed_factor" => 0.8807],
            ["name" => "Smooth Fox Terrier", "expected_life_id" => 6, "breed_factor" => 1.0323],
            ["name" => "Snoodle", "expected_life_id" => 6, "breed_factor" => 0.9842],
            ["name" => "Snowshoe", "expected_life_id" => 5, "breed_factor" => 0.5645],
            ["name" => "Soft Coated Wheaten Terrier", "expected_life_id" => 6, "breed_factor" => 1.0827],
            ["name" => "Somali", "expected_life_id" => 6, "breed_factor" => 0.5920],
            ["name" => "Spanish Bulldog", "expected_life_id" => 5, "breed_factor" => 1.4183],
            ["name" => "Spanish Mastiff", "expected_life_id" => 3, "breed_factor" => 2.3957],
            ["name" => "Spanish Water Dog", "expected_life_id" => 5, "breed_factor" => 0.9535],
            ["name" => "Sphynx", "expected_life_id" => 7, "breed_factor" => 0.6722],
            ["name" => "Spinone Italiano", "expected_life_id" => 6, "breed_factor" => 1.2691],
            ["name" => "Spitz", "expected_life_id" => 6, "breed_factor" => 1.0827],
            ["name" => "St. Johns Waterdog", "expected_life_id" => 5, "breed_factor" => 0.9384],
            ["name" => "Stabyhoun (Stabij)", "expected_life_id" => 6, "breed_factor" => 1.1537],
            ["name" => "Staffordshire Bull Terrier", "expected_life_id" => 6, "breed_factor" => 1.2100],
            ["name" => "Standard Schnauzer", "expected_life_id" => 6, "breed_factor" => 1.1000],
            ["name" => "Sussex Spaniel", "expected_life_id" => 6, "breed_factor" => 1.1722],
            ["name" => "Swedish Elkhound", "expected_life_id" => 5, "breed_factor" => 0.9384],
            ["name" => "Swedish Lapphund", "expected_life_id" => 5, "breed_factor" => 0.9384],
            ["name" => "Swedish Vallhund", "expected_life_id" => 6, "breed_factor" => 1.1909],
            ["name" => "Telomian", "expected_life_id" => 5, "breed_factor" => 1.0488],
            ["name" => "Terrier", "expected_life_id" => 5, "breed_factor" => 0.8264],
            ["name" => "Terripoo", "expected_life_id" => 8, "breed_factor" => 0.9091],
            ["name" => "Tervuren Belgian Shepherd", "expected_life_id" => 6, "breed_factor" => 1.0827],
            ["name" => "Texas Blue Lacey", "expected_life_id" => 7, "breed_factor" => 0.9687],
            ["name" => "Thai", "expected_life_id" => 5, "breed_factor" => 0.5645],
            ["name" => "Thai Ridgeback", "expected_life_id" => 3, "breed_factor" => 1.0323],
            ["name" => "Tibetan Mastiff", "expected_life_id" => 4, "breed_factor" => 2.3208],
            ["name" => "Tibetan Spaniel", "expected_life_id" => 8, "breed_factor" => 0.7880],
            ["name" => "Tibetan Terrier", "expected_life_id" => 6, "breed_factor" => 0.9687],
            ["name" => "Tiffany", "expected_life_id" => 8, "breed_factor" => 0.5735],
            ["name" => "Tonkinese", "expected_life_id" => 6, "breed_factor" => 0.6111],
            ["name" => "Tosa", "expected_life_id" => 4, "breed_factor" => 1.8580],
            ["name" => "Toy Fox Terrier", "expected_life_id" => 6, "breed_factor" => 0.8397],
            ["name" => "Toy Manchester Terrier", "expected_life_id" => 3, "breed_factor" => 1.0323],
            ["name" => "Toy Poodle", "expected_life_id" => 8, "breed_factor" => 0.7513],
            ["name" => "Toy Terrier", "expected_life_id" => 6, "breed_factor" => 1.1909],
            ["name" => "Toyger", "expected_life_id" => 10, "breed_factor" => 0.5920],
            ["name" => "Treeing Tennessee Brindle", "expected_life_id" => 5, "breed_factor" => 1.0323],
            ["name" => "Treeing Walker Coon Hound", "expected_life_id" => 5, "breed_factor" => 1.1355],
            ["name" => "Turkish Angora", "expected_life_id" => 8, "breed_factor" => 0.5735],
            ["name" => "Turkish Van", "expected_life_id" => 6, "breed_factor" => 0.6512],
            ["name" => "Victorian Bulldog", "expected_life_id" => 3, "breed_factor" => 1.0000],
            ["name" => "Vizsla", "expected_life_id" => 6, "breed_factor" => 1.2894],
            ["name" => "Walker Hound", "expected_life_id" => 5, "breed_factor" => 1.1909],
            ["name" => "Weimaraner", "expected_life_id" => 4, "breed_factor" => 1.2894],
            ["name" => "Welsh Corgi-Cardigan", "expected_life_id" => 6, "breed_factor" => 1.1355],
            ["name" => "Welsh Corgi-Pembroke", "expected_life_id" => 5, "breed_factor" => 1.2294],
            ["name" => "Welsh Sheepdog (Welsh Collie)", "expected_life_id" => 6, "breed_factor" => 0.9384],
            ["name" => "Welsh Springer Spaniel", "expected_life_id" => 6, "breed_factor" => 1.1722],
            ["name" => "Welsh Terrier", "expected_life_id" => 4, "breed_factor" => 1.1355],
            ["name" => "West Highland White Terrier", "expected_life_id" => 8, "breed_factor" => 0.9842],
            ["name" => "Westmoreland Terrier", "expected_life_id" => 8, "breed_factor" => 1.0323],
            ["name" => "Wheaten Terrier", "expected_life_id" => 6, "breed_factor" => 1.0000],
            ["name" => "Whippet", "expected_life_id" => 6, "breed_factor" => 1.0488],
            ["name" => "White Doberman", "expected_life_id" => 5, "breed_factor" => 1.4183],
            ["name" => "Wire Haired Fox Terrier", "expected_life_id" => 6, "breed_factor" => 1.1722],
            ["name" => "Wirehaired Pointing Griffon", "expected_life_id" => 4, "breed_factor" => 1.1000],
            ["name" => "Wirehaired Vizsla", "expected_life_id" => 6, "breed_factor" => 1.0160],
            ["name" => "Xoloscuintle", "expected_life_id" => 6, "breed_factor" => 1.0488],
            ["name" => "York Chocolate", "expected_life_id" => 7, "breed_factor" => 0.5827],
            ["name" => "Yorkiepoo", "expected_life_id" => 7, "breed_factor" => 0.7880],
            ["name" => "Yorkshire Terrier", "expected_life_id" => 6, "breed_factor" => 0.7756],
        ];
        
        foreach ($race as $type => $breeds) {
            $breedTypeId = (strtolower($type) === 'chat') ? 1 : 2; 
            foreach ($breeds as $breed) {
                foreach ($breedData as $item) {
                    if ($item['name'] == $breed) {
                        DB::table('breeds')->insert([
                            'name' => $item['name'],
                            'expected_life_id' => $item['expected_life_id'],
                            'breed_factor' => $item['breed_factor'],
                            'breed_type_id' => $breedTypeId,
                        ]);
                    }
                }
            }
        }

        // Form Seeder
        $formCardData = [
            [
                'name' => 'Confort',
                'insurance' => '75%',
                'insurance_factor' => 0.89,
                'annual_limit' => 10000,
                'annual_limit_factor' => 0.702,
                'advantage' => 'Non applicable',
            ],
            [
                'name' => 'Complet',
                'insurance' => '80%',
                'insurance_factor' => 1.066,
                'annual_limit' => 12000,
                'annual_limit_factor' => 0.8814,
                'advantage' => 'inclus',
            ],
            [
                'name' => 'Premium',
                'insurance' => '90%',
                'insurance_factor' => 1.224,
                'annual_limit' => 15000,
                'annual_limit_factor' => 1.066,
                'advantage' => 'inclus',
            ],
        ];

        foreach ($formCardData as $data) {
            FormCard::create($data);
        }


        // Guarrantee seeder
        $guarantees = [
            // chat
            ["logo" => "images/aide.png", "price" => 150, "title" => "Aide à la recherche", "description" => "Bénéficiez d'une aide pouvant atteindre 250 DH pour retrouver votre compagnon en cas de perte ou de vol." , "form_card_id" => 1, "breed_type_id" => 1],
            ["logo" => "images/capital.png", "price" => 100, "title" => "Capital décès de l'animal de compagnie", "description" => "250 DH pour les chats ou 250 DH pour les chiens.", "form_card_id" => 1, "breed_type_id" => 1],
            ["logo" => "images/vetamine.png", "price" => 100, "title" => "Vitamines", "description" => "Remboursement des vitamines prescrites par votre vétérinaire dans la limite de 50 DH.", "form_card_id" => 1, "breed_type_id" => 1],
            ["logo" => "images/responsabilite.png", "price" => 150, "title" => "Responsabilité civile", "description" => " Prise en charge des dommages corporels (à hauteur de 50 000DH) et/ou matériels (à hauteur de 5000 DH) causés à un tiers par votre animal.", "form_card_id" => 1, "breed_type_id" => 1],
            ["logo" => "images/nutrition.png", "price" => 80, "title" => "Nutrition", "description" => "Produits nutritionnels et compléments alimentaires à valeur diététique.", "form_card_id" => 1, "breed_type_id" => 1],
            
            ["logo" => "images/aide.png", "price" => 150, "title" => "Aide à la recherche", "description" => "Bénéficiez d'une aide pouvant atteindre 250 DH pour retrouver votre compagnon en cas de perte ou de vol." , "form_card_id" => 2, "breed_type_id" => 1],
            ["logo" => "images/capital.png", "price" => 100, "title" => "Capital décès de l'animal de compagnie", "description" => "250 DH pour les chats ou 250 DH pour les chiens.", "form_card_id" => 2, "breed_type_id" => 1],
            ["logo" => "images/vetamine.png", "price" => 100, "title" => "Vitamines", "description" => "Remboursement des vitamines prescrites par votre vétérinaire dans la limite de 50 DH.", "form_card_id" => 2, "breed_type_id" => 1],
            ["logo" => "images/responsabilite.png", "price" => 150, "title" => "Responsabilité civile", "description" => " Prise en charge des dommages corporels (à hauteur de 50 000DH) et/ou matériels (à hauteur de 5000 DH) causés à un tiers par votre animal.", "form_card_id" => 2, "breed_type_id" => 1],
            ["logo" => "images/nutrition.png", "price" => 80, "title" => "Nutrition", "description" => "Produits nutritionnels et compléments alimentaires à valeur diététique.", "form_card_id" => 2, "breed_type_id" => 1],
            
            ["logo" => "images/aide.png", "price" => 150, "title" => "Aide à la recherche", "description" => "Bénéficiez d'une aide pouvant atteindre 250 DH pour retrouver votre compagnon en cas de perte ou de vol." , "form_card_id" => 3, "breed_type_id" => 1],
            ["logo" => "images/capital.png", "price" => 100, "title" => "Capital décès de l'animal de compagnie", "description" => "250 DH pour les chats ou 250 DH pour les chiens.", "form_card_id" => 3, "breed_type_id" => 1],

            
            // chien
            ["logo" => "images/aide.png", "price" => 150, "title" => "Aide à la recherche", "description" => "Bénéficiez d'une aide pouvant atteindre 250 DH pour retrouver votre compagnon en cas de perte ou de vol." , "form_card_id" => 1, "breed_type_id" => 2],
            ["logo" => "images/capital.png", "price" => 100, "title" => "Capital décès de l'animal de compagnie", "description" => "250 DH pour les chats ou 250 DH pour les chiens.", "form_card_id" => 1, "breed_type_id" => 2],
            ["logo" => "images/vetamine.png", "price" => 100, "title" => "Vitamines", "description" => "Remboursement des vitamines prescrites par votre vétérinaire dans la limite de 50 DH.", "form_card_id" => 1, "breed_type_id" => 2],
            ["logo" => "images/responsabilite.png", "price" => 150, "title" => "Responsabilité civile", "description" => " Prise en charge des dommages corporels (à hauteur de 50 000DH) et/ou matériels (à hauteur de 5000 DH) causés à un tiers par votre animal.", "form_card_id" => 1, "breed_type_id" => 2],
            ["logo" => "images/nutrition.png", "price" => 80, "title" => "Nutrition", "description" => "Produits nutritionnels et compléments alimentaires à valeur diététique.", "form_card_id" => 1, "breed_type_id" => 2],
            
            ["logo" => "images/aide.png", "price" => 150, "title" => "Aide à la recherche", "description" => "Bénéficiez d'une aide pouvant atteindre 250 DH pour retrouver votre compagnon en cas de perte ou de vol." , "form_card_id" => 2, "breed_type_id" => 2],
            ["logo" => "images/capital.png", "price" => 100, "title" => "Capital décès de l'animal de compagnie", "description" => "250 DH pour les chats ou 250 DH pour les chiens.", "form_card_id" => 2, "breed_type_id" => 2],
            ["logo" => "images/vetamine.png", "price" => 100, "title" => "Vitamines", "description" => "Remboursement des vitamines prescrites par votre vétérinaire dans la limite de 50 DH.", "form_card_id" => 2, "breed_type_id" => 2],
            ["logo" => "images/responsabilite.png", "price" => 150, "title" => "Responsabilité civile", "description" => " Prise en charge des dommages corporels (à hauteur de 50 000DH) et/ou matériels (à hauteur de 5000 DH) causés à un tiers par votre animal.", "form_card_id" => 2, "breed_type_id" => 2],
            ["logo" => "images/nutrition.png", "price" => 80, "title" => "Nutrition", "description" => "Produits nutritionnels et compléments alimentaires à valeur diététique.", "form_card_id" => 2, "breed_type_id" => 2],
            
            ["logo" => "images/aide.png", "price" => 150, "title" => "Aide à la recherche", "description" => "Bénéficiez d'une aide pouvant atteindre 250 DH pour retrouver votre compagnon en cas de perte ou de vol." , "form_card_id" => 3, "breed_type_id" => 2],
            ["logo" => "images/capital.png", "price" => 100, "title" => "Capital décès de l'animal de compagnie", "description" => "250 DH pour les chats ou 250 DH pour les chiens.", "form_card_id" => 3, "breed_type_id" => 2],
        ];
        
        DB::table("guarantees")->insert($guarantees);

    }
}
